### PR TITLE
Upgrade to upstream 4.0.0

### PR DESCRIPTION
**Pull request by antoniochiappetta-elevatelabs**
Rebases the [upstream version `4.0.0`](https://github.com/Appboy/appboy-segment-ios/releases) on top of our forked master, in order to update this destination SDK to be compatible with Segment's SDK `v4.1.0` (we're on `4.1.2`) and Braze's SDK `v4.0.1` (we're on this version).

I followed this [guide to sync a fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) and used a rebase onto our master to fix a few small conflicts, but I'm not sure this is our standard way of doing it.

### CODE REVIEW

**Comment by aboedo** [comment]
When this is ready, you might wanna open up a PR against the main repo from Appboy, since it contains bug fixes that should be useful for everyone who uses the repo

**Comment by antoniochiappetta-elevatelabs** [comment]
> When this is ready, you might wanna open up a PR against the main repo from Appboy, since it contains bug fixes that should be useful for everyone who uses the repo

Thanks, @aboedo! I'll discuss that with the team 👌🏻

**Review by jerelevine — APPROVED** [review]
LGTM

**Comment by antoniochiappetta-elevatelabs** [comment]
@jerelevine As Andrés suggested, it would be great to go back to the original repo by opening up a PR with our changes. I was trying to look into why this wasn't done before, and found this comment of yours:

> It seems like the original repo doesn't really handle the custom endpoint properly unless we can set that somewhere else

Can you better explain to me what issue we were having here?

**Comment by aboedo** [comment]
@antoniochiappetta-elevatelabs I was there when we opened up the fork, so I can provide some historical context.

The answer is that we just didn't really realize that we should, sadly. We did let the Braze team (at the time, they were called Appboy) know of the bug at the time, and they acknowledged it, so we figured they'd fix it. But then years went by and I guess both us and Braze forgot about it. In fact, when we started working on Balance, we ran into the same bug again, let them know once more, but it might have just not been high enough in the priorities list that they could work on it. 

@tonidero might remember a bit more, though.

**Comment by tonidero** [comment]
Yup I remember that happening... I think originally it was only an issue with threading on the `identify` calls. I'm not sure of the later changes to the custom endpoint though...

**Pull request merged**
